### ISSUE TITLE
参数克隆

### ISSUE THREAD

**Issue by tangdf** [fish-li/ClownFish.net#3]
https://github.com/fish-li/ClownFish.net/blob/0a6536f3f5d5cb1020663c4db4e1b776e83241d7/src/ClownFish.Data/Command/BaseCommand.cs#L47-L62

常见数据库驱动实现的`DbParameter`都实现了`ICloneable`接口，可以转换为接口后调用`Clone`方法。

下面是实现了`ICloneable`接口的资料。

`OracleParameter`：<https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleParameterClass.htm#ODPNT1724>；

`SqlParameter`：<https://msdn.microsoft.com/zh-cn/library/system.data.sqlclient.sqlparameter.aspx#Anchor_1>；

`MySqlParameter`：<https://dev.mysql.com/doc/dev/connector-net/6.10/html/T_MySql_Data_MySqlClient_MySqlParameter.htm#ID2RBToggle>；

`SQLiteParameter`：<https://github.com/OpenDataSpace/System.Data.SQLite/blob/5807315bc3d424e1e7e34bed5fef38e67e2ed2d4/System.Data.SQLite/SQLiteParameter.cs#L18>。

不过有一个例外，微软为ASP.NET Core提供的SQLite驱动没有实现这个接口。
<https://github.com/aspnet/Microsoft.Data.Sqlite/blob/a2b6f5f7d0d9aea44ec2af8060acfc9c5fb37847/src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs#L17-L21>。

**Comment by fish-li** [comment]
代码已优化，多谢反馈。
https://github.com/fish-li/ClownFish.net/commit/e072bc51b6599c018d5e2b32454fbc2aa31abfcc
